//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPM.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Noticia
    {
        public int id { get; set; }
        public string titulo { get; set; }
        public string descripcion { get; set; }
        public string lugar { get; set; }
        public System.DateTime fecha { get; set; }
        public string fotoDefault { get; set; }
        public Nullable<bool> estatus { get; set; }
        public string usuarioRegistro { get; set; }
        public string usuarioUpdate { get; set; }
        public Nullable<System.DateTime> fechaRegistro { get; set; }
        public Nullable<System.DateTime> fechaUpdate { get; set; }
    }
}
